### ISSUE TITLE
Integrate login with Twitter

### ISSUE THREAD

**Issue by VenkatVenkatesh** [DashboardHub/TribeDashboard#21]
#2

**Comment by eddiejaoude** [comment]
@VenkatVenkatesh if stories can only be closed once they are merged (or not needed etc). The PR for this story https://github.com/DashboardHub/TribeDashboard/pull/45 has not been merged.

**Comment by VenkatVenkatesh** [comment]
Could you please let me know the reason for closing the PR.

**Comment by eddiejaoude** [comment]
I didn't close it, you did. That was my question to you in the PR 😉 

<img width="1054" alt="Screenshot 2019-04-11 11 12 02" src="https://user-images.githubusercontent.com/624760/55949509-ad84af00-5c4a-11e9-8931-e56a2cb57189.png">

**Comment by VenkatVenkatesh** [comment]
Apologies, There was a network issue. I closed it 👍

**Comment by eddiejaoude** [comment]
No problem
