### ISSUE TITLE
Update subscribers and followers count

### ISSUE THREAD

**Issue by VenkatVenkatesh** [DashboardHub/TribeDashboard#26]
#3 

Include documentation steps for setting up the cron, ideally this is achievable by config in the repo

**Comment by VenkatVenkatesh** [comment]
This task is to create a cloud function, that would run every 24 hours to fetch all the user's social account's (github and twitter) details like subscribers, followers...etc and store them in a new collection called `socialStatsHistory` and would contain daywise followers, subscribers, follows counts. Something like

{
   "twitter": {
       "createdOn": "",
       "subscribers":""
      "followers": "",
      "unfollowers": "",
   }
}

**Comment by eddiejaoude** [comment]
Note: Store `followers`, `newFollowers`, `unfollowers` as sub collections so they are not brought back with the parent document.

---

Day 1 with followers 10
Up - / Down -
```
{
"twitter": {
      "createdOn": "",
      "subscriberCount": 10
      "followerCount": 2,
      "unfollowerCount": 2,
      "followers": ['user a', 'user b', 'user c', 'user d', 'user e', 'user f'],
      "unfollowers": []
   }
}
```

---

Day 2 with followers 10

Up 1 / Down 2

```
{
"twitter": {
      "createdOn": "",
      "subscriberCount": 10
      "followerCount": 2,
      "unfollowerCount": 2,
      "followers": ['user a', 'user b', 'user c', 'user d', 'user g'],
      "newFollowers": ['user g'],
      "unfollowers": ['user e', 'user f']
   }
}
```
---

Day 3 with followers 10

Up 2 / Down 1

```
{
"twitter": {
      "createdOn": "",
      "subscriberCount": 10
      "followerCount": 2,
      "unfollowerCount": 2,
      "followers": ['user b', 'user c', 'user d', 'user g', 'user h', 'user i'],
      "newFollowers": ['user h', 'user i'],
      "unfollowers": ['user a']
   }
}
```

**Comment by VenkatVenkatesh** [comment]
@eddiejaoude To update the userSocial stats of twitter, we have the following twitter Api that returns the user stats.

[Twitter show API](https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-users-show)

The above API accepts Bearer token based authorization as show in the example request in the above link.

- If we use bearer token method we have to generate bearer token once for our application and it can be used for accessing all the userSocial stats of twitter users. 
FYI - [Generate Bearer token](https://developer.twitter.com/en/docs/basics/authentication/guides/bearer-tokens)

I am going with bearer token approach @eddiejaoude. Shall we create a separate config collection where we can store the bearer token of the application.

**Comment by eddiejaoude** [comment]
The collect will only have 1 item in it? Its usually best not to store application specific keys in the code or database, but as environment variables https://firebase.google.com/docs/functions/config-env

**Comment by VenkatVenkatesh** [comment]
Sounds good. Thank you 👍
