### ISSUE TITLE
Public Urls to show user dashboard

### ISSUE THREAD

**Issue by VenkatVenkatesh** [DashboardHub/TribeDashboard#28]
#3

**Comment by eddiejaoude** [comment]
Public url examples

`TribeDashboard.io/GitHub/Username`
`TribeDashboard.io/Twitter/Username`

**Comment by VenkatVenkatesh** [comment]
So the implementation would take care of mostly these three scenarios.

- User who is logged in and loads their dashboard -> Show the dashboard and show action buttons like edit...etc
- User who is logged in and loads another user's dashboard -> Only read mode
- User who is not logged in and loads another user's dashboard - Only read mode

Thinking of setting two flags in the front end code. `isLoggedIn` and `isOwner` should take care of all the three scenarios above. 

Simply, only show the action buttons when `isLoggedIn` and `isOwner` is true.

**Comment by VenkatVenkatesh** [comment]
- [ ]

**Comment by SrijithRad** [comment]
Thought about this a little bit. There might be a scenario that we might not have discussed.

So, let's say a user signed up using Github and connected their Twitter account.
Now, 
- When the User goes to `tribedashboard.com/github/user/`, we get their dashboard and show the github and twitter details
- What should happen when they go to `tribedashboard/twitter/user/`? Should be show all their data as they would see when they go to `tribedashboard/github/user/`? Or Should we say they are not a user? In the latter case, we might need to know which social account is the user's primary account.

@eddiejaoude

**Comment by eddiejaoude** [comment]
I would suggest keeping it simple and the user can only have 1 primary social account and the rest are just connected.

> What should happen when they go to tribedashboard/twitter/user/? Should be show all their data as they would see when they go to tribedashboard/github/user/? Or Should we say they are not a user? In the latter case, we might need to know which social account is the user's primary account.

So in that situation, I think there would be 2 outcomes:
- if no one has logged in with that social and username, then display not found
- if someone (may be themselves or may be someone else) has logged in with that social and username, they would get a readonly version of it

I am open to suggestions if anyone can see a simpler options?

**Comment by SrijithRad** [comment]
I agree. So basically, when the user is signed up using `github` and connects their twitter account, their dashboard link would look like `.../github/username`. They could load this dashboard fine but when you try loading `.../twitter/username` it would just say that they are not connected using `twitter`. For this, @VenkatVenkatesh and I just discussed, and agree that there must be a way of finding what the user's primary account is. And I think the `provider` field in the `user` collection would be the one that they signed up with, in this case, `github`. Any other accounts they connect would just go into the `socialAccounts` collection and would be linked back to the user. 

Do i make sense?

**Comment by eddiejaoude** [comment]
yeah makes sense 👍

**Comment by VenkatVenkatesh** [comment]
Agreed. Created story #53 as a precursor to this one so users can link their accounts back to the primary account they signed up with

**Comment by VenkatVenkatesh** [comment]
@eddiejaoude Please check the following workflow for the public url implementation

- When the user signsUp, we would be hitting a cloud function to generate the public url.

- The cloud function will accept the providerId (github, twitter, instagram, youtube) and userName as input and will generate the public url 

- The public url should be stored in the userCollection.

- So when the user hits the public url in the browser, we would be implementing functionality in the front-end to show the 

- The above approach will be done only for the primary account of the user.

**Comment by eddiejaoude** [comment]
I don't think this is needed. On the UI when they go to `provider/username` we just serve up a public version of the users dashboash

**Comment by VenkatVenkatesh** [comment]
Okay @eddiejaoude . Thank you. so how we will intimate the user that this is their public url which can be shared with other users. Should we show a link in the setting page or in the dashboard ?

**Comment by eddiejaoude** [comment]
Maybe in the settings? See which makes more sense
