### ISSUE TITLE
Add firestore to the angular app.

### ISSUE THREAD

**Issue by VenkatVenkatesh** [DashboardHub/TribeDashboard#30]
#3

**Comment by VenkatVenkatesh** [comment]
Add Firestore to the App. 
Store the data obtained through the Integrations in a generic format.

**Comment by eddiejaoude** [comment]
@VenkatVenkatesh just checking you saw this reply https://github.com/orgs/DashboardHub/teams/tribedashboard/discussions/4/comments/5

**Comment by eddiejaoude** [comment]
Could you redirect the `/` to the login page or add a button from the `/` to the login page (which ever is easiest) for the moment while we dont have anything on the `/`. Thanks

**Comment by VenkatVenkatesh** [comment]
Sure. Will Add some buttons.

**Comment by VenkatVenkatesh** [comment]
Completed

**Comment by VenkatVenkatesh** [comment]
@eddiejaoude Moving  the issue to in progress as Twitter normalization is pending

**Comment by VenkatVenkatesh** [comment]
@eddiejaoude. Shall I create a new branch and start working on twitter.  could you please let me know whether we have to create a new issue or we can use the existing issue. In case of new branch can we name it as `issue-30|twitter`

**Comment by eddiejaoude** [comment]
I created the epics but I am leaving the stories (issues) down to you, the smaller  we can make them the better. If you can create a new issue and branch that would be great 👍

**Comment by VenkatVenkatesh** [comment]
Cool Will do it.
