### ISSUE TITLE
functionality to create payment for the user.

### ISSUE THREAD

**Issue by VenkatVenkatesh** [DashboardHub/TribeDashboard#32]
#5

**Comment by VenkatVenkatesh** [comment]
closing the issue.

**Comment by eddiejaoude** [comment]
> closing the issue.

When adding comments, please add `why` things have occurred not `what`, GitHub will show its been closed in the timeline, but we don't know why 😜

**Comment by VenkatVenkatesh** [comment]
Closed the issue as the stories need to be refactored.
