### ISSUE TITLE
Save secondary user social and stats history in firestore

### ISSUE THREAD

**Issue by VenkatVenkatesh** [DashboardHub/TribeDashboard#61]
#53 
 

- After successful connect of linked secondary account, save the corresponding user social and stats history in firestore

**Comment by VenkatVenkatesh** [comment]
Hi @eddiejaoude, There is an issue when we connected  multiple accounts. Let me brief the issue and the approaches to solve it. Please let me know your thoughts on the suggested approaches.
- Once the user logsIn,  the firestore auth will be returning their userId through which we fetch their documents and render the data in the dashboard. But when we connect to other accounts through dashboard , the firebase auth state is getting changed and it is returning the userId of the newly connected user. Due to this the dashboard renders the data of the connected account and not the primary account. 

**Approaches to solve the issue:**

- Store the primayUserId in the connected user document and fetch the data. By this way, there will be two way binding between the accounts.

- Instead of using `signInWithPopup` use `linkWithPopup`.
FYI: https://firebase.google.com/docs/auth/web/account-linking

**Comment by eddiejaoude** [comment]
> Instead of using `singInWithPopup` use `linkWithPopup`

This sounds like the better approach 👍
