### ISSUE TITLE
CI deployment failing due to missing `request`

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/TribeDashboard#79]
<img width="693" alt="Screenshot 2019-05-17 08 53 16" src="https://user-images.githubusercontent.com/624760/57912038-395cad00-7881-11e9-940b-5c96a592f211.png">

**Comment by VenkatVenkatesh** [comment]
Will look into the issue @eddiejaoude

**Comment by eddiejaoude** [comment]
Thank you. Probably needs `request` to be added to `package.json`, but you dont see the error locally because you still have it in `node_modules` - delete that directory locally and reinstall the deps.
